// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  DefaultFirebaseOptions(FirebaseOptions currentPlatform);

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmx3cSfi3zvJXtmeeH59LyXzE7FK1DqJI',
    appId: '1:707520215944:android:4a92a55031233a461bd83d',
    messagingSenderId: '707520215944',
    projectId: 'tukang-travel',
    storageBucket: 'tukang-travel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA68yqSFHDc54BAvSIAZmBBQn30Dv_I21E',
    appId: '1:707520215944:ios:c45b50bd69005c761bd83d',
    messagingSenderId: '707520215944',
    projectId: 'tukang-travel',
    storageBucket: 'tukang-travel.appspot.com',
    androidClientId: '707520215944-0jscob4fb5ri0h0sift9pbh8b5n2mjm3.apps.googleusercontent.com',
    iosClientId: '707520215944-50ov8u58faj7n2dm3id4rvt59d8essa6.apps.googleusercontent.com',
    iosBundleId: 'com.tuktra.mobile',
  );
}
